version: 2.1
executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: cimg/ruby:3.1.2
caches:
  - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle
  run_rubocop:
    description: start rubocop
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
  run_specs:
    steps:
      - run:
          name: start specs
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $TEST_FILES
  run_fasterer:
    steps:
      - run:
          name: start fasterer
          command: bundle exec fasterer
jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_rubocop
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs
  run_fasterer:
    executor: default
    steps:
      - defaults
      - run_fasterer

workflows:
  version: 2
  build:
    jobs:
      - lintering
      - run_specs
      - run_fasterer